### ISSUE TITLE
Inconsistent code blocks

### ISSUE THREAD

**Issue by changliu98** [mmcdan01/CIS_454#2]
`TabError: inconsistent use of tabs and spaces in indentation`  
please use text editor to check these 3 errors though it shows normally on html

https://github.com/mmcdan01/CIS_454/blob/72e7a140194289d3bbb21e0cc8c059f7a9a422fd/Main.py#L298
https://github.com/mmcdan01/CIS_454/blob/72e7a140194289d3bbb21e0cc8c059f7a9a422fd/Main.py#L302
https://github.com/mmcdan01/CIS_454/blob/72e7a140194289d3bbb21e0cc8c059f7a9a422fd/Main.py#L360

**Comment by mmcdan01** [comment]
When you say that it shows normally on html, do you mean that it runs fine?

**Comment by yukimuon** [comment]
No it won't run... I guess it got edited on website and some tabs got messed
```
        user = User.query.filter_by(email=email).first()              <--- Many spaces
	first_nameCheck = User.query.filter_by(first_name=first_name).first()            <----- 1 tab

        if user:
            flash('Email already exists.', category='error')
	elif first_nameCheck:
```
Try with mouse selecting. like this line 297 is made up from spaces and line 298 is a tab, interpreter will complain

**Comment by mmcdan01** [comment]
I changed the spacing, pull a fresh Main.py and let me know if you have any other issues.
